version: '3.8'

services:
  # Registrierungs-App
  registration-app:
    build: .
    container_name: registration-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - synapse
    restart: unless-stopped
